### ISSUE TITLE
Roadmap Baca-Quran.id 2.0

### ISSUE THREAD

**Issue by mazipan** [mazipan/baca-quran.id#234]
## Description

🚧 A total rewrite the codebase

## Tasks

Initial Phase:
 
- [ ] Old implementation is move to `v1` branch: https://github.com/mazipan/baca-quran.id/tree/v1
- [ ] Rewrite the app using SvelteKit

Known Issues:

- [ ] Missing title, desc & meta data for each pages
- [ ] Missing bookmark feature
- [ ] Missing play audio
- [ ] Missing add to favorite feature

Improvement Idead for the future

- [ ] Login flow for sync cross-device
