### ISSUE TITLE
Add log activity record

### ISSUE THREAD

**Issue by mazipan** [mazipan/baca-quran.id#287]
## Description

Inspired by the log activity report from the elementary school when Ramadhan.

## Tasks

- [ ] Show calendar inline
- [ ] Add record per date
  - [ ] 5 Shalat --> yes/no question
- [ ] Save in local storage

Possible structure:

```js
{
  "YYYY-MM-DD": {
    1: 1, // 1 is Shubuh, value is 1 or 0
    2: 1, // 2 is Dzuhur 
    3: 0,
    4: 0,
    5: 0,
  }
}
```

**Comment by mazipan** [comment]
Closed #288 #289
